services:
  watchtower:
    image: containrrr/watchtower:latest
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: watchtower

  app:
    image: kahkaar/express-app:latest
    build: .
    ports:
      - "8080:8080"
    container_name: express-app
    restart: always
